# Generated by Django 5.0.6 on 2026-01-10 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0024_shopcategory_alter_breakwindow_options_and_more'),
        ('chat', '0002_public_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['barbershop', 'room_type'], name='chat_chatro_barbers_0a18b1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['customer', 'barbershop'], name='chat_chatro_custome_916ca1_idx'),
        ),
    ]
