# Generated by Django 5.0.6 on 2026-01-10 16:13

import app.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_lastviewed_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lastviewed',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lastviewed',
            name='barbershop',
        ),
        migrations.RemoveField(
            model_name='lastviewed',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={},
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='longitude',
        ),
        migrations.AddField(
            model_name='user',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=app.users.models.user_profile_thumb_upload_to),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='address_line',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.users.models.user_profile_image_upload_to),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='LastViewed',
        ),
    ]
