# Generated by GPT to match AppVersion model (adds app_type)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appversion",
            name="app_type",
            field=models.CharField(
                choices=[("main", "Ana Uygulama"), ("partner", "Partner Uygulaması")],
                default="main",
                help_text="Uygulama tipi (ana / partner)",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appversion",
            unique_together={("platform", "app_type", "version_code")},
        ),
        migrations.AddIndex(
            model_name="appversion",
            index=models.Index(
                fields=["platform", "app_type", "is_active", "-version_code"],
                name="core_appver_plat_type_act_ver_idx",
            ),
        ),
    ]

