# Generated by Django 4.2 on 2024-12-03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_image_thumb'),
    ]

    operations = [
        # Bu migration kasıtlı olarak boşaltılmıştır.
        # Veritabanı tutarsızlıklarını önlemek için sunucuda --fake ile geçilecektir.
    ]
