# Generated by Django 4.2 on 2024-12-03
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_image_thumb'),
    ]

    operations = [
        # UserAddress değişiklikleri
        migrations.AlterModelOptions(
            name='useraddress',
            options={},
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='longitude',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='address_line',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        # User image_thumb ekleme
        migrations.AddField(
            model_name='user',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/thumbs/'),
        ),
        # LastViewed ve Favorite modellerini state'den kaldırıyoruz
        # Veritabanı işlemini RunSQL ile yapıyoruz ama hata verirse yoksayıyoruz
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='LastViewed',
                ),
                migrations.DeleteModel(
                    name='Favorite',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS users_lastviewed CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS users_favorite CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
