# Generated by Kuafora agent on 2026-01-17
#
# NOTE: This migration is intentionally idempotent.
# Some environments may already have these columns (manual hotfix / partial apply).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_lastviewed_unique_together_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE users_user
                      ADD COLUMN IF NOT EXISTS email_verified boolean DEFAULT false NOT NULL;
                    ALTER TABLE users_user
                      ADD COLUMN IF NOT EXISTS email_verified_at timestamp with time zone NULL;
                    """,
                    reverse_sql="""
                    ALTER TABLE users_user DROP COLUMN IF EXISTS email_verified_at;
                    ALTER TABLE users_user DROP COLUMN IF EXISTS email_verified;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="email_verified",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="user",
                    name="email_verified_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
    ]


