# Generated by Kuafora agent on 2026-01-17
#
# Adds EmailVerificationCode model for OTP-based email verification.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_email_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_hash", models.CharField(max_length=128)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_codes",
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="emailverificationcode",
            index=models.Index(fields=["user", "expires_at"], name="users_emailv_user_id_8bb0a3_idx"),
        ),
    ]


