# Generated by Django on 2026-02-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('app_open', 'Uygulama Açıldı'), ('app_close', 'Uygulama Kapandı'), ('app_background', 'Uygulama Arka Plan'), ('app_foreground', 'Uygulama Ön Plan')], max_length=20)),
                ('app_type', models.CharField(choices=[('main', 'Ana Uygulama'), ('partner', 'Partner Uygulaması')], max_length=10)),
                ('session_id', models.CharField(db_index=True, help_text="Oturum ID'si", max_length=100)),
                ('device_id', models.CharField(db_index=True, help_text='Cihaz benzersiz ID', max_length=200)),
                ('platform', models.CharField(help_text='iOS, Android, Web', max_length=20)),
                ('app_version', models.CharField(blank=True, help_text='Uygulama versiyonu', max_length=50)),
                ('os_version', models.CharField(blank=True, help_text='İşletim sistemi versiyonu', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, help_text='Kullanıcı giriş yapmamışsa null olabilir', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_app_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('favorite_toggle', 'Favori Ekleme/Çıkarma'), ('review_create', 'Yorum Oluşturma'), ('search', 'Arama'), ('filter', 'Filtreleme'), ('map_view', 'Harita Görünümü'), ('appointment_create', 'Randevu Oluşturma'), ('campaign_view', 'Kampanya Görüntüleme'), ('chat_send', 'Mesaj Gönderme'), ('profile_edit', 'Profil Düzenleme'), ('settings_change', 'Ayarlar Değiştirme')], db_index=True, max_length=50)),
                ('app_type', models.CharField(choices=[('main', 'Ana Uygulama'), ('partner', 'Partner Uygulaması')], max_length=10)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('device_id', models.CharField(db_index=True, max_length=200)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Ek bilgiler (barbershop_id, search_query vb.)')),
                ('success', models.BooleanField(default=True, help_text='İşlem başarılı mı?')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_feature_usages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScreenView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(db_index=True, help_text='Ekran adı (örn: HomeScreen, BarberDetailScreen)', max_length=200)),
                ('app_type', models.CharField(choices=[('main', 'Ana Uygulama'), ('partner', 'Partner Uygulaması')], max_length=10)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('device_id', models.CharField(db_index=True, max_length=200)),
                ('view_duration', models.FloatField(blank=True, help_text='Görüntüleme süresi (saniye)', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Ek bilgiler (barbershop_id, campaign_id vb.)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screen_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_screen_views',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('device_id', models.CharField(db_index=True, max_length=200)),
                ('app_type', models.CharField(choices=[('main', 'Ana Uygulama'), ('partner', 'Partner Uygulaması')], max_length=10)),
                ('platform', models.CharField(max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('start_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, help_text='Oturum süresi (saniye)', null=True)),
                ('screen_count', models.IntegerField(default=0, help_text='Görüntülenen ekran sayısı')),
                ('event_count', models.IntegerField(default=0, help_text='Toplam event sayısı')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_user_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='appevent',
            index=models.Index(fields=['timestamp', 'event_type'], name='analytics_a_timesta_idx'),
        ),
        migrations.AddIndex(
            model_name='appevent',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_a_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='appevent',
            index=models.Index(fields=['app_type', 'timestamp'], name='analytics_a_app_ty_idx'),
        ),
        migrations.AddIndex(
            model_name='appevent',
            index=models.Index(fields=['session_id'], name='analytics_a_session_idx'),
        ),
        migrations.AddIndex(
            model_name='screenview',
            index=models.Index(fields=['timestamp', 'screen_name'], name='analytics_s_timesta_idx'),
        ),
        migrations.AddIndex(
            model_name='screenview',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_s_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='screenview',
            index=models.Index(fields=['app_type', 'screen_name'], name='analytics_s_app_ty_idx'),
        ),
        migrations.AddIndex(
            model_name='screenview',
            index=models.Index(fields=['session_id'], name='analytics_s_session_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['timestamp', 'feature_type'], name='analytics_f_timesta_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_f_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['app_type', 'feature_type'], name='analytics_f_app_ty_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['session_id'], name='analytics_f_session_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['start_time', 'end_time'], name='analytics_u_start__idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'start_time'], name='analytics_u_user_id_start_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['app_type', 'start_time'], name='analytics_u_app_ty_start_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_id'], name='analytics_u_session_idx'),
        ),
    ]

