# Generated by Django 5.0.6 on 2026-01-12 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("booking", "Randevu"),
                            ("chat", "Mesaj"),
                            ("reply", "Yorum Yanıtı"),
                            ("system", "Sistem"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of related object (ör. Appointment / Campaign / Review ID)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim (otomatik)",
                "verbose_name_plural": "Bildirimler (otomatik)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "-created_at"], name="notificatio_user_id_7bdf7d_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "is_read"], name="notificatio_user_id_2dcba6_idx"),
        ),
    ]


