# Generated by Django 5.0.6 on 2026-01-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_broadcastnotification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            old_name="notificatio_user_id_7bdf7d_idx",
            new_name="notificatio_user_id_05b4bc_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            old_name="notificatio_user_id_2dcba6_idx",
            new_name="notificatio_user_id_427e4b_idx",
        ),
        migrations.AlterField(
            model_name="broadcastnotification",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]


