# Generated by Django 5.0.6 on 2026-01-10 16:13

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_customerban_and_more'),
        ('barbers', '0024_shopcategory_alter_breakwindow_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='exclude_overlap_per_staff_active',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_staff_i_b10e5e_idx',
            old_name='appointment_staff_start_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_shop_id_f69843_idx',
            old_name='appointment_shop_start_idx',
        ),
        migrations.RenameIndex(
            model_name='customerban',
            new_name='appointment_user_id_655365_idx',
            old_name='appointments_cust_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='hold',
            new_name='appointment_staff_i_925dee_idx',
            old_name='hold_staff_start_idx',
        ),
        migrations.RenameIndex(
            model_name='hold',
            new_name='appointment_shop_id_2a9851_idx',
            old_name='hold_shop_start_idx',
        ),
        migrations.RenameIndex(
            model_name='hold',
            new_name='appointment_expires_783ed3_idx',
            old_name='hold_expires_idx',
        ),
        migrations.AddField(
            model_name='appointment',
            name='attended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_attended',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'suggested'])), expressions=[(models.Func(models.F('start_datetime'), models.F('end_datetime'), function='tstzrange', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&'), ('staff', '=')], name='exclude_overlap_per_staff_active'),
        ),
    ]
