# Generated by Django 5.0.6 on 2025-11-02 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0009_add_staff_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Oluştur'), ('update', 'Güncelle'), ('delete', 'Sil'), ('override', 'Override Uygula')], max_length=10)),
                ('target_model', models.CharField(help_text='Hangi model değiştirildi', max_length=50)),
                ('target_id', models.IntegerField(help_text="Değiştirilen kaydın ID'si")),
                ('changes', models.JSONField(help_text='Yapılan değişiklikler')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MessageViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text="Cihaz benzersiz ID'si", max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed', models.BooleanField(default=False, help_text="Kullanıcı popup'ı kapattı mı")),
            ],
        ),
        migrations.CreateModel(
            name='OfficialHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('national', 'National'), ('religious', 'Religious'), ('observance', 'Observance')], max_length=12)),
                ('country_code', models.CharField(db_index=True, default='TR', max_length=2)),
                ('year', models.IntegerField(db_index=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Override',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(choices=[('shop_global', 'Dükkan Global Override'), ('staff_individual', 'Personel Override')], max_length=20)),
                ('override_scope', models.CharField(choices=[('full_day_closed', 'Tüm Gün Kapalı'), ('early_closing', 'Erken Kapanış'), ('late_opening', 'Geç Açılış'), ('time_range_closed', 'Belirli Saat Aralığı Kapalı')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Boşsa tek gün, doluysa tarih aralığı', null=True)),
                ('start_time', models.TimeField(blank=True, help_text="Saat aralığı override'ları için", null=True)),
                ('end_time', models.TimeField(blank=True, help_text="Saat aralığı override'ları için", null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_rule', models.CharField(blank=True, help_text='Örn: her ayın ilk pazartesi', max_length=100)),
                ('reason', models.CharField(blank=True, help_text='Override sebebi', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Override aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShopHolidayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('closed', 'Closed all day'), ('open', 'Open all day'), ('custom_hours', 'Custom hours')], max_length=20)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ShopWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False, help_text='Bu gün tamamen kapalı mı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('automatic', 'Otomatik (Sistem)'), ('manual', 'Manuel (Admin)')], max_length=10)),
                ('display_type', models.CharField(choices=[('banner', 'Banner (Sayfada Kart)'), ('popup', 'Popup (Girişte Diyalog)')], default='banner', max_length=10)),
                ('target_type', models.CharField(choices=[('all_shop', 'Tüm Dükkan'), ('specific_staff', 'Belirli Personel(ler)')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('priority', models.IntegerField(default=0, help_text='Yüksek sayı = yüksek öncelik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service__name'],
            },
        ),
        migrations.CreateModel(
            name='StaffServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category__name'],
            },
        ),
        migrations.CreateModel(
            name='StaffWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField(blank=True, help_text='Boşsa dükkan saatlerini devralır', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Boşsa dükkan saatlerini devralır', null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Bu gün personel çalışmıyor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Hangi personele yapılan yorum (opsiyonel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='barbers.staff'),
        ),
        migrations.AlterField(
            model_name='dailyoverride',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='barbers_fav_user_id_3bb9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='lastviewed',
            index=models.Index(fields=['user', '-viewed_at'], name='barbers_las_user_id_c4f2a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'barbershop', 'staff'), name='unique_user_barbershop_staff_review'),
        ),
        migrations.AddField(
            model_name='calendarauditlog',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_audit_logs', to='barbers.barbershop'),
        ),
        migrations.AddField(
            model_name='calendarauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageviewlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='officialholiday',
            unique_together={('country_code', 'date')},
        ),
        migrations.AddField(
            model_name='override',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='barbers.barbershop'),
        ),
        migrations.AddField(
            model_name='override',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='override',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='barbers.staff'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='barbers.review'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='barbers.barbershop'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='barbers.servicecategory'),
        ),
        migrations.AddField(
            model_name='shopholidayoverride',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_overrides', to='barbers.barbershop'),
        ),
        migrations.AddField(
            model_name='shopholidayoverride',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopworkinghours',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_working_hours', to='barbers.barbershop'),
        ),
        migrations.AddField(
            model_name='specialmessage',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_messages', to='barbers.barbershop'),
        ),
        migrations.AddField(
            model_name='specialmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialmessage',
            name='target_staff',
            field=models.ManyToManyField(blank=True, related_name='targeted_messages', to='barbers.staff'),
        ),
        migrations.AddField(
            model_name='messageviewlog',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='barbers.specialmessage'),
        ),
        migrations.AddField(
            model_name='staffservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_offerings', to='barbers.service'),
        ),
        migrations.AddField(
            model_name='staffservice',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='barbers.staff'),
        ),
        migrations.AddField(
            model_name='staffservicecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_offerings', to='barbers.servicecategory'),
        ),
        migrations.AddField(
            model_name='staffservicecategory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_categories', to='barbers.staff'),
        ),
        migrations.AddField(
            model_name='staffworkinghours',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_working_hours', to='barbers.staff'),
        ),
        migrations.AddField(
            model_name='viewevent',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='barbers.barbershop'),
        ),
        migrations.AddField(
            model_name='viewevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbershop_view_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reviewreply',
            unique_together={('review', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='servicecategory',
            unique_together={('barbershop', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='shopholidayoverride',
            unique_together={('barbershop', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='shopworkinghours',
            unique_together={('barbershop', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='messageviewlog',
            unique_together={('message', 'device_id')},
        ),
        migrations.AlterUniqueTogether(
            name='staffservice',
            unique_together={('staff', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='staffservicecategory',
            unique_together={('staff', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='staffworkinghours',
            unique_together={('staff', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='viewevent',
            index=models.Index(fields=['barbershop', '-viewed_at'], name='barbers_vie_barbers_745aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='viewevent',
            index=models.Index(fields=['barbershop', 'user'], name='barbers_vie_barbers_ea70d5_idx'),
        ),
    ]

