# Generated by Django 5.0.6 on 2026-01-10 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0023_breakwindow_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # NOTE:
        # Earlier migration `0018_shopcategory_staff_photo_thumb` creates the
        # `barbers_shopcategory` (and M2M) tables via raw SQL (idempotent) but does NOT
        # update Django migration state. In a fresh DB this makes this migration try to
        # create a table that already exists -> DuplicateTable.
        #
        # Fix: update STATE as if we created the model, but make DB ops idempotent.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS barbers_shopcategory (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(100) NOT NULL,
                        slug varchar(50) NOT NULL DEFAULT '' UNIQUE,
                        icon varchar(100) NULL,
                        is_active boolean NOT NULL DEFAULT TRUE
                    );
                    """,
                    reverse_sql="DROP TABLE IF EXISTS barbers_shopcategory;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ShopCategory",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(max_length=100)),
                        ("slug", models.SlugField(default="", unique=True)),
                        ("icon", models.ImageField(blank=True, null=True, upload_to="categories/icons/")),
                        ("is_active", models.BooleanField(default=True)),
                    ],
                    options={
                        "verbose_name_plural": "Shop Categories",
                    },
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name='breakwindow',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='breakwindow',
            name='breakwindow_start_before_end',
        ),
        migrations.RemoveIndex(
            model_name='breakwindow',
            name='barbers_bre_barbers_3d472a_idx',
        ),
        migrations.RemoveIndex(
            model_name='breakwindow',
            name='barbers_bre_staff_i_1aeaf4_idx',
        ),
        migrations.RemoveIndex(
            model_name='breakwindow',
            name='bw_shop_scope_date_start',
        ),
        migrations.RemoveIndex(
            model_name='breakwindow',
            name='bw_staff_date_start',
        ),
        migrations.RenameIndex(
            model_name='viewevent',
            new_name='barbers_vie_barbers_713c98_idx',
            old_name='barbers_vie_barbers_abc123_idx',
        ),
        migrations.RemoveField(
            model_name='breakwindow',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='barbershop',
            name='external_booking',
            field=models.JSONField(blank=True, default=dict, help_text='Harici randevu yontemleri: whatsapp, website, instagram, other_app, custom'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='main_image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='barbershops/main/thumbs/'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='system_type',
            field=models.CharField(choices=[('info', 'Information'), ('booking', 'Kuafora Booking'), ('external', 'External Booking')], default='info', help_text='Isletme sistem modu: info, booking veya external', max_length=15),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barbershopimage',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='barbershops/extra/thumbs/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='appointment_interval',
            field=models.PositiveIntegerField(choices=[(5, '5 dk'), (10, '10 dk'), (15, '15 dk'), (20, '20 dk'), (30, '30 dk')], default=15, help_text='Randevu aralığı (dakika)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='auto_approval',
            field=models.BooleanField(default=False, help_text='Randevular otomatik onayla mı?'),
        ),
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(blank=True, help_text='Personel hakkında açıklama'),
        ),
        migrations.AddField(
            model_name='staff',
            name='career_start_year',
            field=models.PositiveIntegerField(blank=True, help_text='Kuaförlüğe başladığı yıl (YYYY)', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Personelin yaptığı hizmetten alacağı pay (yüzde)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Kuaförlük deneyimi (yıl)', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender_preference',
            field=models.CharField(choices=[('all', 'Herkese Hizmet'), ('male', 'Sadece Erkek'), ('female', 'Sadece Kadın')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='photo_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/thumbs/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='rating_avg',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Uzmanlık etiketleri: ['boyama_ustasi', '20_yillik_usta', ...]"),
        ),
        migrations.AddField(
            model_name='staff',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='breakwindow',
            name='created_by',
            field=models.ForeignKey(help_text='Molayı ekleyen kullanıcı', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='breakwindow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schedulechangerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS barbers_barbershop_categories (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        barbershop_id bigint NOT NULL REFERENCES barbers_barbershop(id) DEFERRABLE INITIALLY DEFERRED,
                        shopcategory_id bigint NOT NULL REFERENCES barbers_shopcategory(id) DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT barbers_barbershop_categories_barbershop_id_shopcategory_id_uniq
                            UNIQUE (barbershop_id, shopcategory_id)
                    );
                    CREATE INDEX IF NOT EXISTS barbers_barbershop_categories_barbershop_id_idx
                        ON barbers_barbershop_categories(barbershop_id);
                    CREATE INDEX IF NOT EXISTS barbers_barbershop_categories_shopcategory_id_idx
                        ON barbers_barbershop_categories(shopcategory_id);
                    """,
                    reverse_sql="DROP TABLE IF EXISTS barbers_barbershop_categories;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="barbershop",
                    name="categories",
                    field=models.ManyToManyField(blank=True, related_name="barbershops", to="barbers.shopcategory"),
                ),
            ],
        ),
    ]
