# Generated by Django (service_duration_interval for fixed service duration steps)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbers", "0028_fix_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="barbershop",
            name="service_duration_interval",
            field=models.PositiveIntegerField(
                choices=[(10, "10 dk"), (15, "15 dk"), (20, "20 dk")],
                default=15,
                help_text="Hizmet süresi aralığı (dakika); süreler bu değerin katı olarak seçilir",
            ),
        ),
    ]
