server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 301 https://api.kuafora.com$request_uri;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    ssl_certificate /etc/letsencrypt/live/api.kuafora.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.kuafora.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/api.kuafora.com/chain.pem;

    return 301 https://api.kuafora.com$request_uri;
}


