# Generated by Django 5.0.6 on 2026-01-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed_amount', 'Fixed Amount'), ('fixed_price', 'Fixed Price')], max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='system_type',
            field=models.CharField(choices=[('booking', 'Booking System'), ('info', 'Info System'), ('both', 'Both')], default='both', help_text='Hangi sistemlerde geçerli olduğu', max_length=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('time_based', 'Time Based'), ('bundle', 'Bundle'), ('special', 'Special/Condition')], max_length=20),
        ),
    ]
