FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

WORKDIR /app

# Daha dayanıklı apt (retry + ca-certificates)
RUN apt-get update -o Acquire::Retries=3 \
    && apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
        curl \
        ca-certificates \
        cron \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install gunicorn==22.0.0

COPY . /app/

RUN mkdir -p /app/staticfiles /app/media

COPY entrypoint.prod.sh /app/entrypoint.prod.sh
COPY cron_entrypoint.sh /app/cron_entrypoint.sh
RUN chmod +x /app/entrypoint.prod.sh /app/cron_entrypoint.sh

RUN groupadd -r django && useradd -r -g django django
RUN chown -R django:django /app
USER django

EXPOSE 8000
ENTRYPOINT ["/app/entrypoint.prod.sh"]